# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BafangTuner.ui',
# licensing of 'BafangTuner.ui' applies.
#
# Created: Tue Jun 22 15:31:38 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(972, 782)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/ghost.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelMade = QtWidgets.QLabel(self.centralwidget)
        self.labelMade.setGeometry(QtCore.QRect(620, 50, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelMade.setFont(font)
        self.labelMade.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelMade.setObjectName("labelMade")
        self.pushButtonReadAll = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonReadAll.setEnabled(False)
        self.pushButtonReadAll.setGeometry(QtCore.QRect(620, 670, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonReadAll.setFont(font)
        self.pushButtonReadAll.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.pushButtonReadAll.setObjectName("pushButtonReadAll")
        self.comboBoxPorts = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxPorts.setGeometry(QtCore.QRect(610, 160, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxPorts.setFont(font)
        self.comboBoxPorts.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.comboBoxPorts.setObjectName("comboBoxPorts")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 591, 721))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.tabWidget.setObjectName("tabWidget")
        self.tabBasic = QtWidgets.QWidget()
        self.tabBasic.setObjectName("tabBasic")
        self.pushButtonRead = QtWidgets.QPushButton(self.tabBasic)
        self.pushButtonRead.setEnabled(False)
        self.pushButtonRead.setGeometry(QtCore.QRect(20, 630, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.pushButtonRead.setFont(font)
        self.pushButtonRead.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.pushButtonRead.setObjectName("pushButtonRead")
        self.pushButtonWrite = QtWidgets.QPushButton(self.tabBasic)
        self.pushButtonWrite.setEnabled(False)
        self.pushButtonWrite.setGeometry(QtCore.QRect(180, 630, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.pushButtonWrite.setFont(font)
        self.pushButtonWrite.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/burn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonWrite.setIcon(icon1)
        self.pushButtonWrite.setObjectName("pushButtonWrite")
        self.layoutWidget = QtWidgets.QWidget(self.tabBasic)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 110, 541, 498))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.spinBoxAssist0 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxAssist0.setFont(font)
        self.spinBoxAssist0.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist0.setMaximum(100)
        self.spinBoxAssist0.setProperty("value", 10)
        self.spinBoxAssist0.setObjectName("spinBoxAssist0")
        self.gridLayout.addWidget(self.spinBoxAssist0, 1, 1, 1, 1)
        self.spinBoxSpeedlimit0 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxSpeedlimit0.setFont(font)
        self.spinBoxSpeedlimit0.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit0.setMaximum(100)
        self.spinBoxSpeedlimit0.setProperty("value", 10)
        self.spinBoxSpeedlimit0.setObjectName("spinBoxSpeedlimit0")
        self.gridLayout.addWidget(self.spinBoxSpeedlimit0, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.spinBoxAssist1 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxAssist1.setFont(font)
        self.spinBoxAssist1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist1.setMaximum(100)
        self.spinBoxAssist1.setProperty("value", 20)
        self.spinBoxAssist1.setObjectName("spinBoxAssist1")
        self.gridLayout.addWidget(self.spinBoxAssist1, 2, 1, 1, 1)
        self.spinBoxSpeedlimit1 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxSpeedlimit1.setFont(font)
        self.spinBoxSpeedlimit1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit1.setMaximum(100)
        self.spinBoxSpeedlimit1.setProperty("value", 20)
        self.spinBoxSpeedlimit1.setObjectName("spinBoxSpeedlimit1")
        self.gridLayout.addWidget(self.spinBoxSpeedlimit1, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.spinBoxAssist2 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxAssist2.setFont(font)
        self.spinBoxAssist2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist2.setMaximum(100)
        self.spinBoxAssist2.setProperty("value", 30)
        self.spinBoxAssist2.setObjectName("spinBoxAssist2")
        self.gridLayout.addWidget(self.spinBoxAssist2, 3, 1, 1, 1)
        self.spinBoxSpeedlimit2 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxSpeedlimit2.setFont(font)
        self.spinBoxSpeedlimit2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit2.setMaximum(100)
        self.spinBoxSpeedlimit2.setProperty("value", 30)
        self.spinBoxSpeedlimit2.setObjectName("spinBoxSpeedlimit2")
        self.gridLayout.addWidget(self.spinBoxSpeedlimit2, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.spinBoxAssist3 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxAssist3.setFont(font)
        self.spinBoxAssist3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist3.setMaximum(100)
        self.spinBoxAssist3.setProperty("value", 40)
        self.spinBoxAssist3.setObjectName("spinBoxAssist3")
        self.gridLayout.addWidget(self.spinBoxAssist3, 4, 1, 1, 1)
        self.spinBoxSpeedlimit3 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxSpeedlimit3.setFont(font)
        self.spinBoxSpeedlimit3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit3.setMaximum(100)
        self.spinBoxSpeedlimit3.setProperty("value", 40)
        self.spinBoxSpeedlimit3.setObjectName("spinBoxSpeedlimit3")
        self.gridLayout.addWidget(self.spinBoxSpeedlimit3, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_10.setFont(font)
        self.label_10.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.spinBoxAssist4 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxAssist4.setFont(font)
        self.spinBoxAssist4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist4.setMaximum(100)
        self.spinBoxAssist4.setProperty("value", 50)
        self.spinBoxAssist4.setObjectName("spinBoxAssist4")
        self.gridLayout.addWidget(self.spinBoxAssist4, 5, 1, 1, 1)
        self.spinBoxSpeedlimit4 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxSpeedlimit4.setFont(font)
        self.spinBoxSpeedlimit4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit4.setMaximum(100)
        self.spinBoxSpeedlimit4.setProperty("value", 50)
        self.spinBoxSpeedlimit4.setObjectName("spinBoxSpeedlimit4")
        self.gridLayout.addWidget(self.spinBoxSpeedlimit4, 5, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.spinBoxAssist5 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxAssist5.setFont(font)
        self.spinBoxAssist5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist5.setMaximum(100)
        self.spinBoxAssist5.setProperty("value", 60)
        self.spinBoxAssist5.setObjectName("spinBoxAssist5")
        self.gridLayout.addWidget(self.spinBoxAssist5, 6, 1, 1, 1)
        self.spinBoxSpeedlimit5 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxSpeedlimit5.setFont(font)
        self.spinBoxSpeedlimit5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit5.setMaximum(100)
        self.spinBoxSpeedlimit5.setProperty("value", 60)
        self.spinBoxSpeedlimit5.setObjectName("spinBoxSpeedlimit5")
        self.gridLayout.addWidget(self.spinBoxSpeedlimit5, 6, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.spinBoxAssist6 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxAssist6.setFont(font)
        self.spinBoxAssist6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist6.setMaximum(100)
        self.spinBoxAssist6.setProperty("value", 70)
        self.spinBoxAssist6.setObjectName("spinBoxAssist6")
        self.gridLayout.addWidget(self.spinBoxAssist6, 7, 1, 1, 1)
        self.spinBoxSpeedlimit6 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxSpeedlimit6.setFont(font)
        self.spinBoxSpeedlimit6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit6.setMaximum(100)
        self.spinBoxSpeedlimit6.setProperty("value", 70)
        self.spinBoxSpeedlimit6.setObjectName("spinBoxSpeedlimit6")
        self.gridLayout.addWidget(self.spinBoxSpeedlimit6, 7, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_11.setFont(font)
        self.label_11.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 0, 1, 1)
        self.spinBoxAssist7 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxAssist7.setFont(font)
        self.spinBoxAssist7.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist7.setMaximum(100)
        self.spinBoxAssist7.setProperty("value", 80)
        self.spinBoxAssist7.setObjectName("spinBoxAssist7")
        self.gridLayout.addWidget(self.spinBoxAssist7, 8, 1, 1, 1)
        self.spinBoxSpeedlimit7 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxSpeedlimit7.setFont(font)
        self.spinBoxSpeedlimit7.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit7.setMaximum(100)
        self.spinBoxSpeedlimit7.setProperty("value", 80)
        self.spinBoxSpeedlimit7.setObjectName("spinBoxSpeedlimit7")
        self.gridLayout.addWidget(self.spinBoxSpeedlimit7, 8, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_13.setFont(font)
        self.label_13.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 0, 1, 1)
        self.spinBoxAssist8 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxAssist8.setFont(font)
        self.spinBoxAssist8.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist8.setMaximum(100)
        self.spinBoxAssist8.setProperty("value", 90)
        self.spinBoxAssist8.setObjectName("spinBoxAssist8")
        self.gridLayout.addWidget(self.spinBoxAssist8, 9, 1, 1, 1)
        self.spinBoxSpeedlimit8 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxSpeedlimit8.setFont(font)
        self.spinBoxSpeedlimit8.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit8.setMaximum(100)
        self.spinBoxSpeedlimit8.setProperty("value", 90)
        self.spinBoxSpeedlimit8.setObjectName("spinBoxSpeedlimit8")
        self.gridLayout.addWidget(self.spinBoxSpeedlimit8, 9, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_14.setFont(font)
        self.label_14.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 10, 0, 1, 1)
        self.spinBoxAssist9 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxAssist9.setFont(font)
        self.spinBoxAssist9.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxAssist9.setMaximum(100)
        self.spinBoxAssist9.setProperty("value", 100)
        self.spinBoxAssist9.setObjectName("spinBoxAssist9")
        self.gridLayout.addWidget(self.spinBoxAssist9, 10, 1, 1, 1)
        self.spinBoxSpeedlimit9 = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxSpeedlimit9.setFont(font)
        self.spinBoxSpeedlimit9.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedlimit9.setMaximum(100)
        self.spinBoxSpeedlimit9.setProperty("value", 100)
        self.spinBoxSpeedlimit9.setObjectName("spinBoxSpeedlimit9")
        self.gridLayout.addWidget(self.spinBoxSpeedlimit9, 10, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_16.setFont(font)
        self.label_16.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 11, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_18.setFont(font)
        self.label_18.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 12, 0, 1, 1)
        self.spinBoxSpeedMeterSignals = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxSpeedMeterSignals.setFont(font)
        self.spinBoxSpeedMeterSignals.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxSpeedMeterSignals.setMaximum(100)
        self.spinBoxSpeedMeterSignals.setProperty("value", 1)
        self.spinBoxSpeedMeterSignals.setObjectName("spinBoxSpeedMeterSignals")
        self.gridLayout.addWidget(self.spinBoxSpeedMeterSignals, 12, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_19.setFont(font)
        self.label_19.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 13, 0, 1, 1)
        self.comboBoxWheelDiameter = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.comboBoxWheelDiameter.setFont(font)
        self.comboBoxWheelDiameter.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.comboBoxWheelDiameter.setObjectName("comboBoxWheelDiameter")
        self.comboBoxWheelDiameter.addItem("")
        self.comboBoxWheelDiameter.addItem("")
        self.comboBoxWheelDiameter.addItem("")
        self.comboBoxWheelDiameter.addItem("")
        self.comboBoxWheelDiameter.addItem("")
        self.comboBoxWheelDiameter.addItem("")
        self.comboBoxWheelDiameter.addItem("")
        self.comboBoxWheelDiameter.addItem("")
        self.comboBoxWheelDiameter.addItem("")
        self.comboBoxWheelDiameter.addItem("")
        self.comboBoxWheelDiameter.addItem("")
        self.comboBoxWheelDiameter.addItem("")
        self.comboBoxWheelDiameter.addItem("")
        self.comboBoxWheelDiameter.addItem("")
        self.comboBoxWheelDiameter.addItem("")
        self.comboBoxWheelDiameter.addItem("")
        self.gridLayout.addWidget(self.comboBoxWheelDiameter, 13, 1, 1, 1)
        self.comboBoxPorts_2 = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.comboBoxPorts_2.setFont(font)
        self.comboBoxPorts_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.comboBoxPorts_2.setObjectName("comboBoxPorts_2")
        self.comboBoxPorts_2.addItem("")
        self.comboBoxPorts_2.addItem("")
        self.comboBoxPorts_2.addItem("")
        self.gridLayout.addWidget(self.comboBoxPorts_2, 11, 1, 1, 2)
        self.layoutWidget1 = QtWidgets.QWidget(self.tabBasic)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 361, 63))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.spinBoxLowBatteryVoltage = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBoxLowBatteryVoltage.setEnabled(True)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxLowBatteryVoltage.setFont(font)
        self.spinBoxLowBatteryVoltage.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxLowBatteryVoltage.setProperty("value", 30)
        self.spinBoxLowBatteryVoltage.setObjectName("spinBoxLowBatteryVoltage")
        self.gridLayout_2.addWidget(self.spinBoxLowBatteryVoltage, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBoxCurrentLimit = QtWidgets.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBoxCurrentLimit.setFont(font)
        self.spinBoxCurrentLimit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxCurrentLimit.setProperty("value", 15)
        self.spinBoxCurrentLimit.setObjectName("spinBoxCurrentLimit")
        self.gridLayout_2.addWidget(self.spinBoxCurrentLimit, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabBasic, "")
        self.tabPedal = QtWidgets.QWidget()
        self.tabPedal.setObjectName("tabPedal")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tabPedal)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 19, 551, 321))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox_4 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_4.addWidget(self.comboBox_4, 6, 1, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_4.addWidget(self.spinBox_3, 7, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_4.addWidget(self.comboBox, 4, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 10, 0, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_4.addWidget(self.spinBox_4, 8, 1, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_4.addWidget(self.spinBox_5, 9, 1, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout_4.addWidget(self.spinBox_6, 10, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_4.addWidget(self.spinBox, 3, 1, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_4.addWidget(self.spinBox_2, 5, 1, 1, 1)
        self.label_pedal_sensor_type = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_pedal_sensor_type.setFont(font)
        self.label_pedal_sensor_type.setObjectName("label_pedal_sensor_type")
        self.gridLayout_4.addWidget(self.label_pedal_sensor_type, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 2, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_4.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 5, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 3, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 4, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 7, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 8, 0, 1, 1)
        self.comboBox_pedal_sensor_type = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_pedal_sensor_type.setObjectName("comboBox_pedal_sensor_type")
        self.gridLayout_4.addWidget(self.comboBox_pedal_sensor_type, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 6, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_4.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 9, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tabPedal)
        self.label_30.setGeometry(QtCore.QRect(20, 350, 391, 231))
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap(":/newPrefix/SchemaPA.JPG"))
        self.label_30.setObjectName("label_30")
        self.tabWidget.addTab(self.tabPedal, "")
        self.tabThrottle = QtWidgets.QWidget()
        self.tabThrottle.setObjectName("tabThrottle")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tabThrottle)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(19, 19, 541, 201))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 2, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 3, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 4, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 5, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 0, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 1, 0, 1, 1)
        self.spinBox_7 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBox_7.setFont(font)
        self.spinBox_7.setProperty("value", 11)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout_5.addWidget(self.spinBox_7, 0, 1, 1, 1)
        self.spinBox_8 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBox_8.setFont(font)
        self.spinBox_8.setProperty("value", 35)
        self.spinBox_8.setObjectName("spinBox_8")
        self.gridLayout_5.addWidget(self.spinBox_8, 1, 1, 1, 1)
        self.spinBox_9 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.spinBox_9.setFont(font)
        self.spinBox_9.setProperty("value", 20)
        self.spinBox_9.setObjectName("spinBox_9")
        self.gridLayout_5.addWidget(self.spinBox_9, 5, 1, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_5, 2, 1, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_6, 3, 1, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_7, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tabThrottle, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(610, 250, 341, 331))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.groupBox.setObjectName("groupBox")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(340, 60, 311, 16))
        self.label_17.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.label_17.setObjectName("label_17")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 40, 321, 271))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelNominalVoltage_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelNominalVoltage_2.setFont(font)
        self.labelNominalVoltage_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelNominalVoltage_2.setObjectName("labelNominalVoltage_2")
        self.gridLayout_3.addWidget(self.labelNominalVoltage_2, 4, 1, 1, 1)
        self.labelMaxCurrent = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelMaxCurrent.setFont(font)
        self.labelMaxCurrent.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelMaxCurrent.setObjectName("labelMaxCurrent")
        self.gridLayout_3.addWidget(self.labelMaxCurrent, 5, 0, 1, 1)
        self.labelMaxCurrent_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelMaxCurrent_2.setFont(font)
        self.labelMaxCurrent_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelMaxCurrent_2.setObjectName("labelMaxCurrent_2")
        self.gridLayout_3.addWidget(self.labelMaxCurrent_2, 5, 1, 1, 1)
        self.labelFirmVers = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelFirmVers.setFont(font)
        self.labelFirmVers.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelFirmVers.setObjectName("labelFirmVers")
        self.gridLayout_3.addWidget(self.labelFirmVers, 3, 0, 1, 1)
        self.labelModel = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelModel.setFont(font)
        self.labelModel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelModel.setObjectName("labelModel")
        self.gridLayout_3.addWidget(self.labelModel, 1, 0, 1, 1)
        self.labelHardwVers_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHardwVers_2.setFont(font)
        self.labelHardwVers_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelHardwVers_2.setObjectName("labelHardwVers_2")
        self.gridLayout_3.addWidget(self.labelHardwVers_2, 2, 1, 1, 1)
        self.labelManufacturer = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelManufacturer.setFont(font)
        self.labelManufacturer.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelManufacturer.setObjectName("labelManufacturer")
        self.gridLayout_3.addWidget(self.labelManufacturer, 0, 0, 1, 1)
        self.labelFirmVers_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelFirmVers_2.setFont(font)
        self.labelFirmVers_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelFirmVers_2.setObjectName("labelFirmVers_2")
        self.gridLayout_3.addWidget(self.labelFirmVers_2, 3, 1, 1, 1)
        self.labelModel_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelModel_2.setFont(font)
        self.labelModel_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelModel_2.setObjectName("labelModel_2")
        self.gridLayout_3.addWidget(self.labelModel_2, 1, 1, 1, 1)
        self.labelHardwVers = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHardwVers.setFont(font)
        self.labelHardwVers.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelHardwVers.setObjectName("labelHardwVers")
        self.gridLayout_3.addWidget(self.labelHardwVers, 2, 0, 1, 1)
        self.labelNominalVoltage = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelNominalVoltage.setFont(font)
        self.labelNominalVoltage.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelNominalVoltage.setObjectName("labelNominalVoltage")
        self.gridLayout_3.addWidget(self.labelNominalVoltage, 4, 0, 1, 1)
        self.labelManufacturer_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelManufacturer_2.setFont(font)
        self.labelManufacturer_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelManufacturer_2.setObjectName("labelManufacturer_2")
        self.gridLayout_3.addWidget(self.labelManufacturer_2, 0, 1, 1, 1)
        self.pushButtonScan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonScan.setGeometry(QtCore.QRect(900, 160, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonScan.setFont(font)
        self.pushButtonScan.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.pushButtonScan.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/arrow-circle-double.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonScan.setIcon(icon2)
        self.pushButtonScan.setObjectName("pushButtonScan")
        self.pushButtonConnect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonConnect.setEnabled(False)
        self.pushButtonConnect.setGeometry(QtCore.QRect(610, 110, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonConnect.setFont(font)
        self.pushButtonConnect.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/plug-connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonConnect.setIcon(icon3)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.pushButtonDisconnect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDisconnect.setEnabled(False)
        self.pushButtonDisconnect.setGeometry(QtCore.QRect(780, 110, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonDisconnect.setFont(font)
        self.pushButtonDisconnect.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/plug-disconnect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDisconnect.setIcon(icon4)
        self.pushButtonDisconnect.setObjectName("pushButtonDisconnect")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 972, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBoxWheelDiameter.setCurrentIndex(10)
        self.comboBox_6.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Bafang Tuner", None, -1))
        self.labelMade.setText(QtWidgets.QApplication.translate("MainWindow", "Made by Charclo", None, -1))
        self.pushButtonReadAll.setText(QtWidgets.QApplication.translate("MainWindow", "READ ALL", None, -1))
        self.pushButtonRead.setText(QtWidgets.QApplication.translate("MainWindow", "READ", None, -1))
        self.pushButtonWrite.setText(QtWidgets.QApplication.translate("MainWindow", "WRITE", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Assist Levels", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Current limit (%)", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "    Speed limit (%)   ", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Assist 0:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Assist 1:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Assist 2:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Assist 3:", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Assist 4:", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Assist 5:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Assist 6:", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Assist 7:", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Assist 8:", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "Assist 9:", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Speed meter type:", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "Speed Meter Signals:", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "Wheel diameter (Inch):", None, -1))
        self.comboBoxWheelDiameter.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "26", None, -1))
        self.comboBoxWheelDiameter.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "16", None, -1))
        self.comboBoxWheelDiameter.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "17", None, -1))
        self.comboBoxWheelDiameter.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "18", None, -1))
        self.comboBoxWheelDiameter.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "19", None, -1))
        self.comboBoxWheelDiameter.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "20", None, -1))
        self.comboBoxWheelDiameter.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "21", None, -1))
        self.comboBoxWheelDiameter.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "22", None, -1))
        self.comboBoxWheelDiameter.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "23", None, -1))
        self.comboBoxWheelDiameter.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "24", None, -1))
        self.comboBoxWheelDiameter.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "25", None, -1))
        self.comboBoxWheelDiameter.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "26", None, -1))
        self.comboBoxWheelDiameter.setItemText(11, QtWidgets.QApplication.translate("MainWindow", "27", None, -1))
        self.comboBoxWheelDiameter.setItemText(12, QtWidgets.QApplication.translate("MainWindow", "700C", None, -1))
        self.comboBoxWheelDiameter.setItemText(13, QtWidgets.QApplication.translate("MainWindow", "28", None, -1))
        self.comboBoxWheelDiameter.setItemText(14, QtWidgets.QApplication.translate("MainWindow", "29", None, -1))
        self.comboBoxWheelDiameter.setItemText(15, QtWidgets.QApplication.translate("MainWindow", "30", None, -1))
        self.comboBoxPorts_2.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "External, wheel meter", None, -1))
        self.comboBoxPorts_2.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Internal, motor meter", None, -1))
        self.comboBoxPorts_2.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "By motor phase", None, -1))
        self.label.setToolTip(QtWidgets.QApplication.translate("MainWindow", "This is the voltage at which the controller will stop the motor to keep your battery safe from over-discharge. It should be set by the manufacturer properly and you donÔÇÖt need to change it. For 13S battery packs 41V is the default.", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Low Battery Protection (V):", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Current Limit (A):", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBasic), QtWidgets.QApplication.translate("MainWindow", "Basic", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "Keep Current [%]:", None, -1))
        self.label_pedal_sensor_type.setText(QtWidgets.QApplication.translate("MainWindow", "Pedal Sensor Type:", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "Designated Assist Level:", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "Speed Limit:", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "Start Degree: (Signal No.)", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "Start Current [%]: (max 60%)", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "Slow-Start Mode: (1-8)", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "Stop Delay [x10ms]:", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "Current Decay: (1-8)", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "Workmode: (Ang. Pedalspeed/wheel*10)", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "Stop Decay [x10ms]:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPedal), QtWidgets.QApplication.translate("MainWindow", "Pedal Assist", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "Mode:", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "Designated Assist Level:", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("MainWindow", "Speed Limit [km/h]:", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("MainWindow", "Start Current [%]:", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "Start Voltage [x100mV]:", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("MainWindow", "End Voltage [x100mV]:", None, -1))
        self.comboBox_5.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Speed", None, -1))
        self.comboBox_5.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Current", None, -1))
        self.comboBox_6.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "By Display\'s Command", None, -1))
        self.comboBox_6.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_6.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.comboBox_6.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.comboBox_6.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.comboBox_6.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.comboBox_6.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "6", None, -1))
        self.comboBox_6.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "7", None, -1))
        self.comboBox_6.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.comboBox_6.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "9", None, -1))
        self.comboBox_7.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "By Display\'s Command", None, -1))
        self.comboBox_7.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "25", None, -1))
        self.comboBox_7.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "26", None, -1))
        self.comboBox_7.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "40", None, -1))
        self.comboBox_7.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "45", None, -1))
        self.comboBox_7.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "50", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabThrottle), QtWidgets.QApplication.translate("MainWindow", "Throttle Handle", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Controller Info", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Manufacturer:", None, -1))
        self.labelNominalVoltage_2.setText(QtWidgets.QApplication.translate("MainWindow", "N/A", None, -1))
        self.labelMaxCurrent.setText(QtWidgets.QApplication.translate("MainWindow", "Max. Current:", None, -1))
        self.labelMaxCurrent_2.setText(QtWidgets.QApplication.translate("MainWindow", "N/A", None, -1))
        self.labelFirmVers.setText(QtWidgets.QApplication.translate("MainWindow", "Firmware version:", None, -1))
        self.labelModel.setText(QtWidgets.QApplication.translate("MainWindow", "Model:", None, -1))
        self.labelHardwVers_2.setText(QtWidgets.QApplication.translate("MainWindow", "N/A", None, -1))
        self.labelManufacturer.setText(QtWidgets.QApplication.translate("MainWindow", "Manufacturer:", None, -1))
        self.labelFirmVers_2.setText(QtWidgets.QApplication.translate("MainWindow", "N/A", None, -1))
        self.labelModel_2.setText(QtWidgets.QApplication.translate("MainWindow", "N/A", None, -1))
        self.labelHardwVers.setText(QtWidgets.QApplication.translate("MainWindow", "Hardware version:", None, -1))
        self.labelNominalVoltage.setText(QtWidgets.QApplication.translate("MainWindow", "Nominal voltage:", None, -1))
        self.labelManufacturer_2.setText(QtWidgets.QApplication.translate("MainWindow", "N/A", None, -1))
        self.pushButtonConnect.setText(QtWidgets.QApplication.translate("MainWindow", "Connect", None, -1))
        self.pushButtonDisconnect.setText(QtWidgets.QApplication.translate("MainWindow", "Disconnect", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionLoad.setText(QtWidgets.QApplication.translate("MainWindow", "Load configuration", None, -1))
        self.actionLoad.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+L", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "Save configuration", None, -1))
        self.actionSave_as.setText(QtWidgets.QApplication.translate("MainWindow", "Save as", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.actionHelp.setText(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
